fix: `--strict` flag when using `conftest verify` (#866)
Without this `conftest verify --strict` does not fail in situations
where running `conftest test --strict` would.

I think this was probably an oversight with #798 and it was expected
that `conftest verify --strict` should behave the same as `conftest test
--strict`.

Without this change the behaviour is:

```
$ go run . verify --policy examples/strict-rules/policy --strict

0 tests, 0 passed, 0 warnings, 0 failures, 0 exceptions, 0 skipped
```

With this change the behaviour is:

```
$ go run . verify --policy examples/strict-rules/policy --strict
Error: running verification: load: loading policies: get compiler: 4 errors occurred:
examples/strict-rules/policy/lenient.rego:6: rego_compile_error: assigned var b unused
examples/strict-rules/policy/lenient.rego:7: rego_compile_error: assigned var x unused
examples/strict-rules/policy/lenient.rego:11: rego_compile_error: assigned var c unused
examples/strict-rules/policy/lenient.rego:14: rego_compile_error: unused argument y. (hint: use _ (wildcard variable) instead)
exit status 1
```

Signed-off-by: Sam Crang <sam.crang@gmail.com>